services:
  # 1. Base de données PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: flight_db
    environment:
      POSTGRES_DB: flightdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend 
  backend:
    build:
      context: ./backend
    container_name: flight-backend
    ports:
      - "8080:8080"
    environment:
      FLIGHT_API_KEY: ${FLIGHT_API_KEY}
      # Configuration pour que Spring se connecte à la base
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/flightdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    links:
      - db:db

  # 3. Frontend Angular
  frontend:
    build:
      context: ./frontend
    container_name: flight-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data: