# 1. API Configuration
aviationstack.api.key=${FLIGHT_API_KEY}
aviationstack.api.url=https://api.aviationstack.com/v1/flights

# 2. Logging
#logging.level.com.flightbooking=DEBUG
#logging.level.root=DEBUG

# 3. PostgreSQL Configuration (via variables d'environnement Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. JPA/Hibernate pour PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
